exclude: '^docs/conf.py'

repos:
#- repo: https://github.com/pre-commit/pre-commit-hooks
#  rev: v4.6.0
#  hooks:
#  - id: trailing-whitespace
#  - id: check-added-large-files
#  - id: check-ast
#  - id: check-json
#  - id: check-merge-conflict
  # - id: check-xml
#  - id: check-yaml
#  - id: debug-statements
#  - id: end-of-file-fixer
#  - id: requirements-txt-fixer
#  - id: mixed-line-ending
#    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

#- repo: https://github.com/PyCQA/pydocstyle
#  rev: 6.3.0
#  hooks:
#  - id: pydocstyle
#    args: [--convention=numpy]


#- repo: https://github.com/PyCQA/flake8
#  rev: 7.1.0
#  hooks:
#  - id: flake8
#    args: [--docstring-convention=numpy]

#D100 for module, D101 for class
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.0
  hooks:
    - id: flake8
      args: [--docstring-convention=numpy, --select=D100,D101,D102,D103]

#- repo: https://github.com/terrencepreilly/darglint
#  rev: v1.8.1
#  hooks:
#  - id: darglint
#    args: [--docstring-style=numpy]


# - repo: https://github.com/PyCQA/isort
#   rev: 5.13.2
#   hooks:
#   - id: isort

#- repo: https://github.com/psf/black
#  rev: 24.4.2
#  hooks:
#  - id: black
#    language_version: python3

#- repo: https://github.com/PyCQA/flake8
#  rev: 7.1.0
#  hooks:
#  - id: flake8
#    args: [--max-line-length=132]
