# .readthedocs.yml
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"  # specify the Python version

python:
  install:
    - requirements: docs/requirements.txt  # install dependencies from requirements.txt
    # install pyreco package before building the docs
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py  # path to Sphinx configuration file